### ISSUE TITLE
hiding secrets does not work anymore

### ISSUE THREAD

**Issue by OikoumE** [johnpapa/vscode-cloak#47]
when i hit F1->cloak->hide secrets, it just flashes the content of my .env file.

i dont know where else to get support than here. if im completely in the wrong place, please point me to the correct place to get support for this. i rely on this extension working

**Comment by nickytonline** [comment]
I noticed this recently as well. I don't think it's the plugin itself though because I tried a dotenv plugin since this wasn't working, but they have the same issue too. I wonder if there's some new permissions required or if VS Code restricts some things now in regards to extensions. 🤔

What I do notice when I hide secrets is it appears to flicker, so I wonder if it's applying the CSS and reverting immediately for some reason.

Happy to look into this more if others are experiencing it as well.

**Comment by savaonepunch** [comment]
Doesn't work for me either.

**Comment by johnpapa** [comment]
Addressed in 0.4.0

Added new scope for ini files. Fixes change to VS Code scopes where cloak was not hiding secrets.

VS Code appears to have changed how they scope env files.

**Comment by nickytonline** [comment]
Just tested this and it works like a charm. Thanks for the awesome project @johnpapa  and thanks door fixing the issue! 🎉

**Comment by OikoumE** [comment]
can confirm 0.4.1 works :D thanks !

**Comment by kennyclark** [comment]
encountering this issue in `v0.5.0`

**Comment by PabloDinella** [comment]
Had this problem with 0.5.0 as well, turns out I needed to update my vscode (from 1.69 to 1.72).

**Comment by ched-dev** [comment]
I still have this issue in Cloak 0.5.0 and currently running vscode 1.74.2 universal.

Tried uninstalling, reloading, reinstalling but no luck. Any ideas what else I could try?

**Comment by OikoumE** [comment]
I have struggled with cloak, and not bothered trying to find an
alternative, i instead added a 2nd layer to my .env and secret files.
Minimum of 1.5-2 screen heights of blank space before any vars/secrets.
That way i can feel a tiny bit more secure
